---
name: multi-job-
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Buildstep
        run: echo "this is build step"
  test:
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - name: Testing
        run: echo "TEsting the code"
  deploy:
    runs-on: ubuntu-22.04
    needs: test
    steps:
      - name: testing
        run: echo "Deploying the code"
