name: This is the first jobs
on: workflow_dispatch
jobs:
  firstjob:
    runs-on: ubuntu-22.04
    steps:
      - name: first step
        run: echo "Hello This is the first job"

  secondjob:
    needs: firstjob
    runs-on: ubuntu-latest
    steps:
      - name: second job
        run: echo "Hello this is the second job"

        
        
   

